### ISSUE TITLE
Unsupported operation

### ISSUE THREAD

**Issue by priyadars-hi** [SamJakob/croupier#1]
Hello,

We trying to make flutter app for web and while connecting with SocketCluster server error is coming. 

```
Exception has occurred.
"Error: Unsupported operation: Platform._version
    at Object.throw_ [as throw] (http://localhost:57980/dart_sdk.js:5080:11)
    at _Platform._version (http://localhost:57980/dart_sdk.js:57563:17)
    at get version [as version] (http://localhost:57980/dart_sdk.js:57637:27)
    at get _version (http://localhost:57980/dart_sdk.js:57507:27)
    at desc.get [as _version] (http://localhost:57980/dart_sdk.js:5565:17)
    at get version [as version] (http://localhost:57980/dart_sdk.js:57476:26)
    at Object._getHttpVersion (http://localhost:57980/dart_sdk.js:205704:31)
    at new _http._HttpClient.new (http://localhost:57980/dart_sdk.js:200716:28)
    at HttpClient.new (http://localhost:57980/dart_sdk.js:195179:16)
    at get _httpClient (http://localhost:57980/dart_sdk.js:205700:34)
    at desc.get [as _httpClient] (http://localhost:57980/dart_sdk.js:5565:17)
    at _WebSocketImpl.connect (http://localhost:57980/dart_sdk.js:205347:72)
    at WebSocket.connect (http://localhost:57980/dart_sdk.js:204053:35)
    at croupier._SocketClusterClientImpl.new.connect (http://localhost:57980/packages/croupier/croupier.dart.lib.js:944:52)
    at connect.next (<anonymous>)
    at runBody (http://localhost:57980/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:57980/dart_sdk.js:40691:7)
```

Package running fine with command line, but not inside flutter app.  Please help with the solution.

Thanks.

**Comment by SamJakob** [comment]
Hi,

I've actually not tested this package with Flutter for Web and it uses dart:io so I will take a look at what the situation is regarding Flutter for web and get back to you.

**Comment by priyadars-hi** [comment]
Ok, Thanks
